vich_uploader:
    db_driver: orm # ou mongodb si tu utilises MongoDB
    mappings:
        product_media:
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
